
magpie.llm.default.url=http://127.0.0.1:11434/v1
magpie.llm.default.key=ollama

magpie.llm.query.agent.api=default
magpie.llm.query.agent.model=qwen3.5:9b

magpie.llm.applier.api=default
magpie.llm.applier.model=qwen3.5:9b

magpie.llm.planner.api=default
magpie.llm.planner.model=qwen3.5:9b

magpie.llm.reminding.api=default
magpie.llm.reminding.model=qwen3.5:9b

magpie.llm.embedding.api=default
magpie.llm.embedding.model=nomic-embed-text
magpie.llm.embedding.batch=10

default.splitter.max-segment-size=1000
default.splitter.max-overlap-size=100
default.splitter.class=io.github.ihongs.serv.magpie.splitter.DefSplitter
discard.splitter.class=io.github.ihongs.serv.magpie.splitter.DisSplitter

#document.parser=io.github.ihongs.serv.magpie.parser.CmdParser
#document.parse.cmd=${CORE_PATH}/bin/doc-parser/parser.bat
#document.parse.url=http://127.0.0.1:8081/parse|auth_code

# dependency: langchain4j-document-parser-apache-tika
#document.parser=dev.langchain4j.data.document.parser.apache.tika.ApacheTikaDocumentParser
